output "s3_bucket_name" {
  description = "S3 bucket name for static site"
  value       = aws_s3_bucket.site.id
}

output "s3_bucket_arn" {
  description = "S3 bucket ARN"
  value       = aws_s3_bucket.site.arn
}

output "cloudfront_distribution_id" {
  description = "CloudFront distribution ID (for cache invalidation)"
  value       = aws_cloudfront_distribution.site.id
}

output "cloudfront_domain_name" {
  description = "CloudFront distribution domain name"
  value       = aws_cloudfront_distribution.site.domain_name
}

output "site_url" {
  description = "Site URL"
  value       = "https://${var.domain_name}"
}

output "acm_certificate_arn" {
  description = "ACM certificate ARN"
  value       = aws_acm_certificate.site.arn
}

# DNS records to create manually (if not using Route53)
output "dns_validation_records" {
  description = "DNS records for certificate validation (create these if not using Route53)"
  value = !var.use_route53 ? {
    for dvo in aws_acm_certificate.site.domain_validation_options : dvo.domain_name => {
      name  = dvo.resource_record_name
      type  = dvo.resource_record_type
      value = dvo.resource_record_value
    }
  } : {}
}

output "cloudfront_cname_record" {
  description = "CNAME record to create for your domain (if not using Route53)"
  value = !var.use_route53 ? {
    name  = var.domain_name
    type  = "CNAME"
    value = aws_cloudfront_distribution.site.domain_name
  } : null
}

output "route53_zone_id" {
  description = "Route53 zone ID used"
  value       = var.use_route53 ? data.aws_route53_zone.main[0].zone_id : null
}

# Values needed for deploy script
output "deploy_config" {
  description = "Configuration for deploy_s3.py script"
  value = {
    S3_BUCKET     = aws_s3_bucket.site.id
    CLOUDFRONT_ID = aws_cloudfront_distribution.site.id
    AWS_REGION    = var.aws_region
  }
}

# Deploy credentials
output "deploy_user_arn" {
  description = "ARN of the deploy IAM user"
  value       = aws_iam_user.deploy.arn
}

output "deploy_access_key_id" {
  description = "Access key ID for deploy user"
  value       = aws_iam_access_key.deploy.id
}

output "deploy_secret_access_key" {
  description = "Secret access key for deploy user (sensitive)"
  value       = aws_iam_access_key.deploy.secret
  sensitive   = true
}

# Complete .env block for easy copy-paste
output "env_file_content" {
  description = "Content to add to .env file for deploy script"
  sensitive   = true
  value       = <<-EOT
    # AWS Deploy Credentials (generated by Terraform)
    S3_BUCKET=${aws_s3_bucket.site.id}
    CLOUDFRONT_ID=${aws_cloudfront_distribution.site.id}
    AWS_REGION=${var.aws_region}
    AWS_ACCESS_KEY_ID=${aws_iam_access_key.deploy.id}
    AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.deploy.secret}
  EOT
}
